export const API_BASE_URL = import.meta.env.VITE_API_URL;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: `/api/auth/login`,
    REGISTER: `/api/auth/register`,
    LOGOUT: `/api/auth/logout`,
    FORGOT_PASSWORD: `/api/auth/forgot-password`,
    RESET_PASSWORD: `/api/auth/reset-password`,
    RESEND_VERIFICATION: `/api/auth/resend-verification-email`,
    VERIFY_EMAIL: `/api/auth/verify-email`,
  },
  ADMIN: {
    // ME: `/api/users/me`,
    // GET_ALL: `/api/users/`,
    // GET_BY_ID: (id: string) => `/api/users/${id}`,
    // UPDATE: (id: string) => `/api/users/${id}`,
    GET_ALL: `/api/patients/admin/all`,
    GET_BY_ID: (id: string) => `/api/patients/admin/${id}`,
    GET_ADMIN_PROFILE: `/api/users/profile`,  
    UPDATE: (id: string) => `/api/patients/admin/${id}`,
    PATIENT_STATUS_UPDATE: (id: string) => `/api/patients/admin/${id}/status`,
    DELETE: (id: string) => `/api/patients/admin/${id}`,
    GET_ALL_DOCTORS: `/api/doctors/admin/all`,
    GET_DOCTOR_BY_ID: (id: string) => `/api/doctors/admin/${id}`,
    VERIFY_DOCTOR: (id: string) => `/api/doctors/admin/${id}/verify`,
    DELETE_DOCTOR: (id: string) => `/api/doctors/admin/${id}`,
    ENABLE_2FA: `/api/users/2fa/enable`,  
    VERIFY_TWOFA: `/api/users/2fa/verify`,  
    DISABLE_TWOFA: `/api/users/2fa/disable`,   
    CHANGE_PASSWORD: `/api/users/change-password`,     
    CREATE_USER: `/api/users/create-admin`,       
  },
  PATIENT: {
    CREATE: `/api/patients/register`,
    GET_PATIENT_PROFILE: `/api/patients/profile`,
    GET_PATIENT_APPOINTMENTS: `/api/patients/appointments`,
    GET_PATIENT_MEDICAL_RECORDS: `/api/patients/medical-records`,
  },
  APPOINTMENT: {
    CREATE: `/api/appointments/`,
    GET_ALL: `/api/appointments/`,
    GET_BY_ID: (id: string) => `/api/appointments/${id}`,
    UPDATE: (id: string) => `/api/appointments/${id}`,
    DELETE: (id: string) => `/api/appointments/${id}`,
  },
  DOCTOR: {
    CREATE: `/api/doctors/register`,
    GET_DOCTOR_PROFILE: `/api/doctors/doctor/profile`,
    UPDATE: (id: string) => `/api/doctors/${id}`,
  },
};
