export const API_BASE_URL = import.meta.env.VITE_API_URL;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: `/api/auth/login`,
    REGISTER: `/api/auth/register`,
    LOGOUT: `/api/auth/logout`,
    FORGOT_PASSWORD: `/api/auth/forgot-password`,
    RESET_PASSWORD: `/api/auth/reset-password`,
    RESEND_VERIFICATION: `/api/auth/resend-verification-email`,
    VERIFY_EMAIL: `/api/auth/verify-email`,
  },
  ADMIN: {
    // ME: `/api/users/me`,
    // GET_ALL: `/api/users/`,
    // GET_BY_ID: (id: string) => `/api/users/${id}`,
    // UPDATE: (id: string) => `/api/users/${id}`,
    GET_ALL: `/api/patients/admin/all`,
    GET_BY_ID: (id: string) => `/api/patients/admin/${id}`,
    GET_ADMIN_PROFILE: `/api/users/profile`,
    UPDATE: (id: string) => `/api/patients/admin/${id}`,
    PATIENT_STATUS_UPDATE: (id: string) => `/api/patients/admin/${id}/status`,
    DELETE: (id: string) => `/api/patients/admin/${id}`,
    GET_ALL_DOCTORS: `/api/doctors/admin/all`,
    GET_DOCTOR_BY_ID: (id: string) => `/api/doctors/admin/${id}`,
    VERIFY_DOCTOR: (id: string) => `/api/doctors/admin/${id}/verify`,
    DELETE_DOCTOR: (id: string) => `/api/doctors/admin/${id}`,
    ENABLE_2FA: `/api/users/2fa/enable`,
    VERIFY_TWOFA: `/api/users/2fa/verify`,
    DISABLE_TWOFA: `/api/users/2fa/disable`,
    CHANGE_PASSWORD: `/api/users/change-password`,
    CREATE_USER: `/api/users/create-admin`,
    GET_ALL_USERS: "/api/users/all",
    USER_STATUS_UPDATE: (userId: string) => `/api/users/${userId}/status`,
    DELETE_USER: (userId: string) => `/api/users/${userId}`,
    GET_DASHBOARD_STATS: "api/doctors/admin/stats/dashboard",
  },
  PATIENT: {
    CREATE: `/api/patients/register`,
    GET_PATIENT_PROFILE: `/api/patients/profile`,
    GET_PATIENT_APPOINTMENTS: `/api/patients/appointments`,
    GET_PATIENT_MEDICAL_RECORDS: `/api/patients/medical-records`,
    GET_PATIENT_DASHBOARD: `/api/patients/dashboard`,
    GET_PATIENT_APPOINTMENT_BY_ID: (appointmentId: string) => `/api/patients/appointments/${appointmentId}`,
  },
  APPOINTMENT: {
    GET_BY_ID: (id: string) => `/api/appointments/${id}`,
    BOOK_APPOINTMENT: `/api/appointments/book`,
    GET_ALL: `/api/appointments/`,
    CANCEL_APPOINTMENT: (id: string) => `/api/appointments/${id}`,
    RESCHEDULE_APPOINTMENT: (id: string) => `/api/appointments/${id}/reschedule`,
    UPDATE_APPOINTMENT_STATUS: (id: string) => `/api/appointments/${id}/status`,
  },
  DOCTOR: {
    CREATE: `/api/doctors/register`,
    GET_DOCTOR_DASHBOARD: `/api/doctors/doctor/dashboard`,
    GET_DOCTOR_ANALYTICS: `/api/doctors/doctor/statistics`,
    GET_DOCTOR_PROFILE: `/api/doctors/doctor/profile`,
    UPDATE_DOCTOR_PROFILE: `/api/doctors/doctor/profile`,
    UPDATE_DOCTOR_PROFILE_PROFESSIONAL_INFO: `/api/doctors/doctor/professional-info`,
    UPDATE_DOCTOR_PROFILE_CONTACT_INFO: `/api/doctors/doctor/contact-info`,
    UPDATE: (id: string) => `/api/doctors/${id}`,
    GET_UNAVAILABLE_DATES: `/api/doctors/doctor/unavailable-dates`,
    GET_UNAVAILABLE_DATES_SUMMARY: `/api/doctors/doctor/unavailable-dates/summary`,
    CREATE_UNAVAILABLE_DATES: `/api/doctors/doctor/unavailable-dates`,
    CREATE_UNAVAILABLE_DATE_RANGE: `/api/doctors/doctor/unavailable-dates/range`,
    UPDATE_UNAVAILABLE_DATES: `/api/doctors/doctor/unavailable-dates/:date`,
    BULK_DELETE_UNAVAILABLE_DATES: `/api/doctors/doctor/unavailable-dates/bulk-remove`,
    DELETE_UNAVAILABLE_DATES: (dateId: string) => `/api/doctors/doctor/unavailable-dates/${dateId}`,
    GET_DOCTOR_FEES: `/api/doctors/doctor/fees`,
    UPDATE_DOCTOR_FEES: `/api/doctors/doctor/fees`,
    ADD_BREAK: "/api/doctors/doctor/schedule/break",
    REMOVE_BREAK: (id: string) => `/api/doctors/doctor/schedule/break/${id}`,
    GET_SCHEDULE: "/api/doctors/doctor/schedule",
    UPDATE_AVAILABILITY: "/api/doctors/doctor/availability",
    UPDATE_SCHEDULE: "/api/doctors/doctor/schedule",
    GET_DOCTOR_APPOINTMENTS: "/api/doctors/doctor/appointments",
    GET_DOCTOR_TODAY_APPOINTMENTS: "/api/doctors/doctor/appointments/today",
    GET_DOCTOR_UPCOMING_APPOINTMENTS: "/api/doctors/doctor/appointments/upcoming",
    GET_DOCTOR_APPOINTMENT_BY_ID: (appointmentId: string) => `/api/doctors/doctor/appointments/${appointmentId}`,
    UPDATE_CONSULTATION: (appointmentId: string) => `/api/doctors/doctor/appointments/${appointmentId}/consultation`,
    UPDATE_APPOINTMENT_STATUS: (appointmentId: string) => `/api/doctors/doctor/appointments/${appointmentId}/status`,
    GET_ALL_DOCTOR_PATIENT: `/api/doctors/doctor/patients`,
    GET_DOCTOR_PATIENT_HISTORY: (patientId: string) => `/api/doctors/doctor/patients/${patientId}/history`,
  },
    PUBLIC: {
    GET_PUBLIC_DOCTOR_LIST: `/api/doctors/list`,
  },
};
